name: javaMaven

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Download repository
        uses: actions/checkout@v2

      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Test with Maven
        run: mvn -B test --file pom.xml
